// Using format! macro 

pub fn my_string() { 
    let s1 = String::from("tic"); 
    let s2 = String::from("tac"); 
    let s3 = String::from("toe"); 

    let s = format!("{s1}-{s2}-{s3}");
} 

// This code sets s to tic-tac-toe 
// The format! macro works like println!, but instead of printing the output to the screen, 
// it returns a String with the contents 
// Using format! is much easier to read, and the code generated by the format! macro uses references 
// so that this call doesn't take ownership of any of its parameters

